---
title: "Gorka Navarrete"
subtitle: "Bayesian reasoning, medical decision making, data visualization, Rstats, metascience"
---

My main research focus is related to Bayesian reasoning, risk communication and medical decision-making, as well as various things such as heuristics and biases and the neural basis of reasoning. I am also part of an international network in the perception of beauty in architectural contexts.

I obtained my PhD in Cognitive Neuroscience in the Universidad de La Laguna (Spain). Worked as a postdoctoral fellow in the University of Hull (UK), Universidad de La Laguna (Spain) and York University (Canada). Currently I am an Adjunct professor at Universidad Adolfo Ibañez in Chile and a substitute professor at Universidad de La Laguna, Spain.  

Besides my research lines, I love Open science and Meta science. I truly believe that science should be as open and reproducible as possible. Also, I love RStats and creating tools to make researcher's life easier. See some of my coding work in my [Github profile](https://github.com/gorkang).  