---
title: "Publications"
author: "Gorka Navarrete"
---

This list of publications has been automagically generated on `r Sys.Date()` using the {[rorcid](https://github.com/ropensci/rorcid)} package and a bit of [R code](https://github.com/gorkang/GN-web/blob/master/publications.qmd). You can directly check my [ORCID profile](https://orcid.org/0000-0001-7678-8656). A copy of the publications can be found in this [shared folder](https://drive.google.com/drive/folders/1oNFC4lcG23MX4B2M097HyAQVRKX9vvAF){target="_blank"}. 

------------------------------------------------------------------------

```{r setup, include=FALSE}

library(dplyr)
library(purrr)
library(rorcid)

knitr::opts_chunk$set(echo = FALSE)
DF = rorcid::orcid_works("0000-0001-7678-8656")

DF_publications_raw = rorcid::orcid_works(orcid = "0000-0001-7678-8656", put_code = DF$`0000-0001-7678-8656`$works$`put-code`)

authors = 1:length(DF_publications_raw$`0000-0001-7678-8656`$works$work.contributors.contributor) |>  
           purrr::map(~ {
             paste(DF_publications_raw$`0000-0001-7678-8656`$works$work.contributors.contributor[[.x]]$`credit-name.value`, collapse = ", ")
             })  |>  
           unlist() |> dplyr::as_tibble() |> dplyr::rename(authors = value)


DF_publications_temp = 
  DF_publications_raw$`0000-0001-7678-8656`$works |> 
  dplyr::bind_cols(authors) |> 
  dplyr::arrange(dplyr::desc(`work.publication-date.year.value`)) |> 
  dplyr::distinct(`work.title.title.value`, .keep_all = TRUE)|> 
  mutate(`work.publication-date.year.value` = 
           case_when(
             `work.title.title.value` == "Cancer screening risk literacy of physicians in training: An experimental study" ~ "2019",
             TRUE ~ `work.publication-date.year.value`
           )) 

# Try again to find DOI
DF_publications = DF_publications_temp |> 
  mutate(DOI2 = 
           seq_along(DF_publications_temp$`work.put-code`) |> 
           map(~{
             DF_publications_temp$`work.external-ids.external-id`[[.x]] |> filter(`external-id-type`  == "doi") |> pull(`external-id-value`)
           })
  ) |> 
  # rowwise() |> 
  mutate(work.url.value = ifelse(is.na(work.url.value), 
                                 paste0("http://dx.doi.org/", DOI2), work.url.value))
  # ungroup()
  
# |> 
#   
#   # Nuevos articulos, aun no en ORCID
#   bind_rows(
#     tibble(
#      authors = "Contreras Taibo, L., Navarrete, G., Pereda, N. y Pinto-Cortez, C.",
#      `work.publication-date.year.value` = "2025",
#      `work.title.title.value` = "Transformación tras la adversidad: crecimiento postraumático en sobrevivientes de violencia sexual infantil", 
#      `work.journal-title.value` = "Anuario de Psicología",
#       work.url.value = "https://doi.org/10.5093/apj2025a10" 
#     )) |> 
#   tidyr::drop_na(`work.put-code`)
```

```{r, results='asis'}

show_paper <- function(DF) {
      paste0("- ", 
          gsub("(.*)(Navarrete)(.*)", "\\1**\\2**\\3", DF$authors), " (",
          DF$`work.publication-date.year.value`, "). ",
          DF$`work.title.title.value`, ", ",
          "*", DF$`work.journal-title.value`, "*. ",
          "[", DF$work.url.value, "](",
          DF$work.url.value, ")",
          "  \n\n")
}

years_pubs = sort(unique(DF_publications$`work.publication-date.year.value`), decreasing = TRUE)



list_PUBS = 1:length(years_pubs) |> 
  purrr::map(~{
    # .x=2
    OUT = paste0("\n## ", years_pubs[.x], "\n")
    
    DF = 
      DF_publications |> 
      dplyr::filter(DF_publications$`work.publication-date.year.value` == years_pubs[.x])
    
    OUT = c(OUT, 
            1:nrow(DF) |> purrr::map_chr(~ show_paper(DF[.x,]))
            )
      
  })

cat(list_PUBS |> unlist())
```
